module.exports = {
    googleclientID: "YOUR GOOGLE CLIENT ID",
    googleclientSecret: "YOUR GOOGLE CLIENT SECRET",
    FACEBOOK_APP_ID: "YOUR FACEBOOK APP ID",
    FACEBOOK_APP_SECRET: "YOUR FACEBOOK APP SECRET",
}
